# Generated by Django 3.2.5 on 2021-10-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='status',
            field=models.CharField(choices=[('venta', 'venta'), ('renta', 'renta')], default='renta', max_length=10),
        ),
    ]
