# Generated by Django 3.2.8 on 2021-10-18 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipodeinmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='tipo_de_inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipodeinmueble'),
        ),
    ]
