# Generated by Django 3.2.8 on 2021-10-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inmueble_tipo_de_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
