# Generated by Django 3.2.8 on 2021-10-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='dias_publicado',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
