# Generated by Django 3.2.8 on 2021-10-28 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211027_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_inmueble', models.ImageField(blank=True, null=True, upload_to='')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inmueble')),
            ],
        ),
    ]
